image: Visual Studio 2022
platform: x64
configuration: Release

build_script:
  - mkdir _build
  - cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build  _build
  - cmake --build _build --config Release

